# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2022-09-07 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libros',
            name='autores',
        ),
        migrations.AddField(
            model_name='libros',
            name='autores',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='libros.Autor'),
            preserve_default=False,
        ),
    ]
